import subprocess
from pathlib import Path
from models import InstallConfig, KernelChoice, Desktop

MOUNT = "/mnt/gentra"


def run_in_chroot(cmd: list[str]) -> subprocess.CompletedProcess:
    """Run a command inside the chroot at /mnt/gentra."""
    return subprocess.run(
        ["chroot", MOUNT] + cmd,
        check=True,
    )


GENTOO_BINHOST = "https://distfiles.gentoo.org/releases/amd64/binpackages/17.1/x86-64/"


def write_make_conf(use_line: str, profile: str = "base", use_binhost: bool = True) -> None:
    """Write USE flags and base settings to /mnt/gentra/etc/portage/make.conf."""
    make_conf = Path(MOUNT) / "etc/portage/make.conf"
    binhost_lines = (
        f'PORTAGE_BINHOST="{GENTOO_BINHOST}"\n'
        'FEATURES="getbinpkg binpkg-request-packages"'
        if use_binhost else ""
    )
    content = f"""# Generated by Gentra installer
COMMON_FLAGS="-O2 -pipe"
CFLAGS="${{COMMON_FLAGS}}"
CXXFLAGS="${{COMMON_FLAGS}}"
FCFLAGS="${{COMMON_FLAGS}}"
FFLAGS="${{COMMON_FLAGS}}"
MAKEOPTS="-j$(nproc)"
{binhost_lines}
{use_line}
"""
    make_conf.write_text(content)


def emerge(packages: list[str], binpkg: bool = True) -> None:
    """Install packages via emerge inside the chroot."""
    flags = ["--quiet", "--nospinner"]
    if binpkg:
        flags.append("--getbinpkg")
    run_in_chroot(["emerge"] + flags + packages)


def enable_services(services: list[str]) -> None:
    """Enable systemd services inside the chroot."""
    for service in services:
        run_in_chroot(["systemctl", "enable", service])


def create_user(username: str, full_name: str, password: str) -> None:
    """Create the primary user account inside the chroot."""
    run_in_chroot(["useradd", "-m", "-G", "wheel,audio,video,plugdev,netdev",
                   "-c", full_name, username])
    subprocess.run(
        ["chroot", MOUNT, "chpasswd"],
        input=f"{username}:{password}\n".encode(),
        check=True,
    )


def install_bootloader(disk: str) -> None:
    """Install GRUB to the given disk."""
    run_in_chroot(["grub-install", "--target=x86_64-efi",
                   "--efi-directory=/boot/efi",
                   f"--bootloader-id=Gentra",
                   disk])
    run_in_chroot(["grub-mkconfig", "-o", "/boot/grub/grub.cfg"])


def install_kernel(choice: KernelChoice) -> None:
    """Install dist-kernel, optionally also run genkernel."""
    emerge(["sys-kernel/gentoo-kernel-bin"])
    if choice == KernelChoice.GENKERNEL:
        emerge(["sys-kernel/genkernel"])
        run_in_chroot(["genkernel", "all"])


def de_packages(desktop: Desktop, full: bool) -> list[str]:
    """Return the list of packages to emerge for the chosen DE and install type."""
    base = {
        Desktop.KDE: ["kde-plasma/plasma-meta"],
        Desktop.GNOME: ["gnome-base/gnome-light"],
        Desktop.XFCE: ["xfce-base/xfce4-meta"],
        Desktop.HYPRLAND: ["gui-wm/hyprland", "gui-apps/waybar", "gui-apps/wofi"],
        Desktop.I3: ["x11-wm/i3", "x11-misc/polybar", "x11-misc/rofi"],
        Desktop.MINIMAL: [],
    }
    extra = {
        Desktop.KDE: ["kde-apps/kde-apps-meta"],
        Desktop.GNOME: ["gnome-base/gnome"],
        Desktop.XFCE: ["xfce-extra/xfce4-goodies"],
        Desktop.HYPRLAND: ["xfce-base/thunar", "x11-terms/foot", "app-editors/micro",
                            "app-text/zathura", "media-gfx/imv"],
        Desktop.I3: ["xfce-base/thunar", "x11-terms/alacritty", "app-editors/micro",
                     "app-text/zathura", "app-misc/feh"],
        Desktop.MINIMAL: [],
    }
    pkgs = list(base[desktop])
    if full:
        pkgs.extend(extra[desktop])
    return pkgs
